name: EKS Deployment

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Read permission for the repo

    env:
      TF_WORKSPACE: dev  # Set the workspace (can be dev, staging, prod, etc.)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS Credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::051826738669:role/custom_OIDC
          aws-region: us-east-1  # AWS region for the resources

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.5  # Specify Terraform version

      # Step 4: Initialize Terraform with Workspace-Specific State
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=etl-pipeline-manny" \
            -backend-config="key=${{ env.TF_WORKSPACE }}/terraform.tfstate" \
            -backend-config="region=us-east-2" \
            -backend-config="dynamodb_table=tf_state_lock"

      # Step 5: Terraform Plan (generate the execution plan)
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Terraform Apply (deploy the infrastructure)
      - name: Terraform Apply
        run: terraform apply -auto-approve

